// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhRgmcH06PoTQLsyk8lndSbgaIH9d_9Bw',
    appId: '1:1033559351828:web:d12ed0fdc0af0fd6e1fd01',
    messagingSenderId: '1033559351828',
    projectId: 'fooddeliveryapp-9d1c8',
    authDomain: 'fooddeliveryapp-9d1c8.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-9d1c8.appspot.com',
    measurementId: 'G-N9T3JLGMS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv6DMV7yz9TweBy8P2HFW4GtIMtXPemR8',
    appId: '1:1033559351828:android:bd83a35001f87294e1fd01',
    messagingSenderId: '1033559351828',
    projectId: 'fooddeliveryapp-9d1c8',
    storageBucket: 'fooddeliveryapp-9d1c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQgKK1mqauLucZMEcWgk7u34TQkmdbnQE',
    appId: '1:1033559351828:ios:db09d801b182a2bae1fd01',
    messagingSenderId: '1033559351828',
    projectId: 'fooddeliveryapp-9d1c8',
    storageBucket: 'fooddeliveryapp-9d1c8.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQgKK1mqauLucZMEcWgk7u34TQkmdbnQE',
    appId: '1:1033559351828:ios:db09d801b182a2bae1fd01',
    messagingSenderId: '1033559351828',
    projectId: 'fooddeliveryapp-9d1c8',
    storageBucket: 'fooddeliveryapp-9d1c8.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhRgmcH06PoTQLsyk8lndSbgaIH9d_9Bw',
    appId: '1:1033559351828:web:740950bd866c76bbe1fd01',
    messagingSenderId: '1033559351828',
    projectId: 'fooddeliveryapp-9d1c8',
    authDomain: 'fooddeliveryapp-9d1c8.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-9d1c8.appspot.com',
    measurementId: 'G-RVVMHJJZMM',
  );
}
